config/routes.rb
Rpt::Application.routes.draw do
  resources :invitados

  resources :fechas do
    collection { post :import }
  end

  
  resources :asignaciones

  resources :actividades

  resources :consultores

  devise_for :consultoras
  resources :proyectos
  resources :customers
  resources :profiles

  get "dashboard/index"
  get "main/index"
  get "perfil_consultoras" => "profiles#index",:as => "Perfil_Consultoras"
  get '/generando_login_consultor/:id', to: 'consultores#register', :as => "register"
  post '/registrar', :to =>  'consultores#register_user'
  get "dashboard" => "dashboard#index",:as => "Dashboard"
  get "clientes" => "customers#index",:as => "Clientes"
  get "clientes", to: "customers#index", :as => "cliente"
  get "/nuevo_cliente", to: "customers#new", :as => "nuevo"
  get "/editando_cliente/:id", to: "customers#edit", :as => "editar"
  get "proyectos" => "proyectos#index",:as => "Proyectos"
  get '/asignaciones_consultor/:id', to: 'consultores#asignar', :as => "asignar"
  get '/consultor/:id', to: 'consultores#edit', :as => "edit"
  post '/asignar', :to =>  'consultores#crear_asignaciones'
  get "/editando_consultor/:id", to: "consultores#edit", :as => "editar_consultor"
  get "/nuevo_consultor", to: "consultores#new", :as => "nuevo_consultor"
  post '/abrir_periodo', :to =>  'actividades#abrir_periodo'
  get '/acceso', to: 'consultores#acceso', :as => "accesso"
  post '/registrar_invitados', :to =>  'consultores#register_invitados'
  post '/acceso', :to =>  'consultores#acceso'
  post '/enviar_email', :to =>  'consultores#enviar_email'

  

  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: "dashboard#index"

end

app/models/actividade.rb
class Actividade < ActiveRecord::Base
	scope :misasignaciones ,-> (asignacion) {where("email = ?", asignacion)}
	scope :ListadoPrincipal ,-> (asignacion, id_consultor) {where("id_consultora = ? and id_consultor = ?", asignacion, id_consultor )}



end

app/models/asignacione.rb
class Asignacione < ActiveRecord::Base
	scope :misasignaciones ,-> (asignacion) {where("email = ?", asignacion)}
	scope :ListadoPrincipal ,-> (asignacion,email) {where("id = ? and email =?", asignacion,email)}
end

app/models/consultora.rb
class Consultora < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:trackable, :timeoutable, :lockable
  scope :existe ,-> (proyecto) {where("email = ?", proyecto)} 
end

app/models/consultore.rb
class Consultore < ActiveRecord::Base
	has_many :proyectos
	has_many :customers
	belongs_to :user

	scope :misconsultores ,-> (consultor) {where("user_id = ?", consultor)}


	
def to_param

"#{id}-#{nombre.gsub(/(\s)/, '-').gsub(/,|\.|\?|'|"/,'')}"
		
end
    
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :proyectos
	has_many :consultores
	belongs_to :profile
	scope :by_clientes ,-> (customer) {where("user_id = ?", customer)}
	scope :list_clientes ,-> (customer) {where("user_id = ?", customer)}
	
	def to_param
		"#{id}-#{nombre.gsub(/(\s)/, '-').gsub(/,|\.|\?|'|"/,'')}"
		end
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
	belongs_to :profile
end

app/models/fecha.rb
class Fecha < ActiveRecord::Base
#Sirve para la importacion de fechas
 require 'csv'
######

## scope ##
scope :MesActual ,-> (asignacion, id_consultor) {where("mes = ? and año = ?", asignacion, id_consultor )}
########### 

  def self.import(file)
    CSV.foreach(file.path, "r:ISO-8859-1" ) do |row|
      
      @fecha = row[0]
      @mes = row[1]
      @dia = row[2]
      @diaL = row[3]
      @mesl = row[4]
      @ano = row[5]
      
      Fecha.create!(:fecha => @fecha,:mes => @mes, :dia => @dia, :diaL => @diaL, :mesl => @mesl,:año => @ano)

    end # end CSV.foreach
  end # end sel
  
end

app/models/invitado.rb
class Invitado < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	self.inheritance_column = nil
	has_many :customers
	has_many :proyectos
	scope :by_user ,-> (profile) {where("user_id = ?", profile)}
		def to_param
		"#{id}-#{nombre.gsub(/(\s)/, '-').gsub(/,|\.|\?|'|"/,'')}"
		end
	
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
	has_many :customers
	belongs_to :profile
	has_many :consultores

	scope :misproyectos ,-> (proyecto) {where("user_id = ?", proyecto)}

def to_param

"#{id}-#{cliente.gsub(/(\s)/, '-').gsub(/,|\.|\?|'|"/,'')}"
		
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  scope :existe ,-> (proyecto) {where("email = ?", proyecto)}      
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @proyectos = Proyecto.misproyectos(current_consultora.id)
    #@proyectos = Proyecto.all
    respond_with(@proyectos)
  end

  def show
    respond_with(@proyecto)
  end

  def new
    @clientes = Customer.by_clientes(current_consultora.id).pluck(:nombre)
    @proyecto = Proyecto.new
    respond_with(@proyecto)
  end

  def edit
    @clientes = Customer.by_clientes(current_consultora.id).pluck(:nombre)
  end

  def create
    @proyecto = Proyecto.new(proyecto_params)
    @proyecto.save
    respond_with(@proyecto)
  end

  def update
    @proyecto.update(proyecto_params)
    respond_with(@proyecto)
  end

  def destroy
    @proyecto.destroy
    respond_with(@proyecto)
  end

  private
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    def proyecto_params
      params.require(:proyecto).permit(:cliente, :nombreProyecto, :lider, :gerente, :user_id)
    end
end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultores_helper.rb
module ConsultoresHelper
	def radio_button_tag(name, value, checked = false, options = {})
        html_options = { "type" => "radio", "name" => name, "id" => "#{sanitize_to_id(name)}_#{sanitize_to_id(value)}", "value" => value }.update(options.stringify_keys)
        html_options["checked"] = "checked" if checked
        tag :input, html_options
      end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/fechas_helper.rb
module FechasHelper
end

app/helpers/invitados_helper.rb
module InvitadosHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/proyectos/_form.html.erb
<%= form_for(@proyecto) do |f| %>
  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% @proyecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente %><br>
    <%= f.select :cliente, options_for_select(@clientes) , :class => "selectpicker" %>
   
  </div>
    <div class="field">
    <%= f.label 'Nombre del Proyecto' %><br>
    <%= f.text_field :nombreProyecto,:class => "form-control tamano" %>
   
  </div>
  <div class="field">
    <%= f.label 'Nombre del Lider Responsable del Proyecto' %><br>
    <%= f.text_field :lider,:class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= f.label 'Nombre del Gerente Resposable del Proyecto' %><br>
    <%= f.text_field :gerente,:class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_consultora.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proyectos/_form_edit.html.erb
<%= form_for(@proyecto) do |f| %>
  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% @proyecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente %><br>
    <%= f.text_field :cliente, :class => "form-control tamano" ,:readonly => true %>
  </div>
    <div class="field">
    <%= f.label 'Nombre del Proyecto' %><br>
    <%= f.text_field :nombreProyecto,:class => "form-control tamano" %>
   
  </div>
  <div class="field">
    <%= f.label 'Nombre del Lider Responsable del Proyecto' %><br>
    <%= f.text_field :lider,:class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= f.label 'Nombre del Gerente Resposable del Proyecto' %><br>
    <%= f.text_field :gerente,:class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_consultora.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<%= render 'pagina/style' %>
<%= render 'pagina/menuE_left' %>
<%= render 'pagina/content_head' %>
<h1>Editing proyecto</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', @proyecto %> |
<%= link_to 'Back', proyectos_path %>
<%= render 'pagina/content_footer' %>

app/views/proyectos/index.html.erb
<%= render 'pagina/style' %>
<%= render 'pagina/menuE_left' %>
<%= render 'pagina/content_head' %>
<h1>Mis Proyectos</h1>
<h5>Número de Proyectos <strong> <%= @proyectos.count %></strong></h5>
<%= link_to 'Nuevo Proyecto', new_proyecto_path , :class => "btn btn-warning btn-cons color" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre del Cliente</th>
      <th>Nombre del Proyecto</th>
      <th>Lider de Proyecto</th>
      <th>Gerente de Proyecto</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @proyectos.each do |proyecto| %>
      <tr>
        <td><%= proyecto.cliente %></td>
        <td><%= proyecto.nombreProyecto %></td>
        <td><%= proyecto.lider %></td>
        <td><%= proyecto.gerente %></td>
 
        <td><%= link_to 'Editar', edit_proyecto_path(proyecto) %></td>
        <td><%= link_to 'Eliminar', proyecto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= render 'pagina/content_footer' %>

app/views/proyectos/new.html.erb
<%= render 'pagina/style' %>
<%= render 'pagina/menuE_left' %>
<%= render 'pagina/content_head' %>
<h1>New proyecto</h1>

<%= render 'form' %>

<%= link_to 'Back', proyectos_path %>
<%= render 'pagina/content_footer' %>

app/views/proyectos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @proyecto.cliente %>
</p>

<p>
  <strong>Lider:</strong>
  <%= @proyecto.lider %>
</p>

<p>
  <strong>Gerente:</strong>
  <%= @proyecto.gerente %>
</p>

<p>
  <strong>User:</strong>
  <%= @proyecto.user_id %>
</p>

<%= link_to 'Edit', edit_proyecto_path(@proyecto) %> |
<%= link_to 'Back', proyectos_path %>