config/routes.rb
Rpt::Application.routes.draw do
  resources :invitados

  resources :fechas do
    collection { post :import }
  end

  
  resources :asignaciones

  resources :actividades

  resources :consultores

  devise_for :consultoras
  resources :proyectos
  resources :customers
  resources :profiles

  get "dashboard/index"
  get "main/index"
  get "perfil_consultoras" => "profiles#index",:as => "Perfil_Consultoras"
  get '/generando_login_consultor/:id', to: 'consultores#register', :as => "register"
  post '/registrar', :to =>  'consultores#register_user'
  get "dashboard" => "dashboard#index",:as => "Dashboard"
  get "clientes" => "customers#index",:as => "Clientes"
  get "clientes", to: "customers#index", :as => "cliente"
  get "/nuevo_cliente", to: "customers#new", :as => "nuevo"
  get "/editando_cliente/:id", to: "customers#edit", :as => "editar"
  get "proyectos" => "proyectos#index",:as => "Proyectos"
  get '/asignaciones_consultor/:id', to: 'consultores#asignar', :as => "asignar"
  get '/consultor/:id', to: 'consultores#edit', :as => "edit"
  post '/asignar', :to =>  'consultores#crear_asignaciones'
  get "/editando_consultor/:id", to: "consultores#edit", :as => "editar_consultor"
  get "/nuevo_consultor", to: "consultores#new", :as => "nuevo_consultor"
  post '/abrir_periodo', :to =>  'actividades#abrir_periodo'
  get '/acceso', to: 'consultores#acceso', :as => "accesso"
  post '/registrar_invitados', :to =>  'consultores#register_invitados'
  post '/acceso', :to =>  'consultores#acceso'
  post '/enviar_email', :to =>  'consultores#enviar_email'

  

  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: "dashboard#index"

end

app/models/consultore.rb
class Consultore < ActiveRecord::Base
	has_many :proyectos
	has_many :customers
	belongs_to :user

	scope :misconsultores ,-> (consultor) {where("user_id = ?", consultor)}


	
def to_param

"#{id}-#{nombre.gsub(/(\s)/, '-').gsub(/,|\.|\?|'|"/,'')}"
		
end
    
end

app/controllers/consultores_controller.rb
class ConsultoresController < ApplicationController
  before_action :set_consultore, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  respond_to :html, :json
  def enviar_email
    @user = params[:correo]
    @consultora = Profile.find_by(:user_id => current_consultora.id)
    Mailer.invitacion(@user,@consultora).deliver
    redirect_to :controller => 'consultores', :action => 'acceso'
  end

  def acceso
    @invitado = Invitado.new
    @invitados = Invitado.where(:id_consultora => current_consultora.id)
    if params[:correo].nil?
       @mensaje = ""
    else  
    @verificaU = User.existe(params[:correo]).count

      if @verificaU == 1 
       @leyenda = "U"
       @mensaje ="El correo " + params[:correo] + " ya existe, desea darle acceso a uno de sus consultores?"
        # Mailer.invitacion(@user).deliver
          else  
            @verificaC = Consultora.existe(params[:correo]).count
          if @verificaC == 1
            @leyenda = "C"
          elsif @verificaC == 0 
            @leyenda = "N"
            @mensaje = "El usuario aun no se encuentra registrado, desea enviarle una invitación para que se registre?"
          end  

      end  
     end 
    @email = params[:correo]
    @users = User.all
    @consultores = Consultore.misconsultores(current_consultora.id).pluck(:email)
  end
 def register_invitados
    #@users = User.find_by(:email => params[:email])

    @user = User.new(:email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation], :invitado => params[:invitado], :email_consultor => params[:email_consultor].to_s, :email_consultora => params[:email_consultora])
   # @user.save
     respond_to do |format|
      if @user.save
        format.html { redirect_to consultores_path, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end
  def index
    #@conteo = Consultore.count('id', :distinct => true)
 
    @consultores = Consultore.misconsultores(current_consultora.id)
    respond_with(@consultores)

  end

  def register
     @consultore = Consultore.find(params[:id])
     @resource ||= User.new
  end

  def register_user
    @consultore = Consultore.find_by(:email => params[:email])
    @user = User.new(:email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation])
   # @user.save
     respond_to do |format|
      if @user.save
         @consultore.update(:access => true)
        format.html { redirect_to consultores_path, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
     @consultores = Consultore.all
  end
    
  def asignar
     @consultore = Consultore.find(params[:id])
     @clientes = Customer.by_clientes(current_consultora.id).pluck(:nombre)
    @proyectos = Proyecto.misproyectos(current_consultora.id).pluck(:nombreProyecto)
  end
    def crear_asignaciones

    @consultore = Consultore.find_by(:email => params[:email])
    @asignacion = Asignacione.new(:id_consultora => params[:id_consultora], :email => params[:email], :cliente => params[:cliente], :proyecto => params[:proyecto], :horaInicio => params[:horaInicio],:horaFin => params[:horaFin])
   # @user.save
     respond_to do |format|
      if @asignacion.save
        # @consultore.update(:access => true)
        format.html { redirect_to consultores_path, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def show
    respond_with(@consultore)
  end

  def new
    @asignaciones = Asignacione.all
    @asignacione = Asignacione.all
    @customers = Customer.list_clientes(current_consultora.id)
    @clientes = Customer.by_clientes(current_consultora.id).pluck(:nombre)
    @proyectos = Proyecto.misproyectos(current_consultora.id).pluck(:nombreProyecto)
    @consultore = Consultore.new
    respond_with(@consultore)
  end

  def edit
    @consultore = Consultore.find(params[:id])
    @email= Consultore.find(params[:id])
    @asignaciones = Asignacione.misasignaciones(@email.email)
  end

  def create
    @consultore = Consultore.new(consultore_params)
    @consultore.save
    respond_with(@consultore)
  end

  def update
    @consultore.update(consultore_params)
    respond_with(@consultore)
  end

  def destroy
    @consultore.destroy
    respond_with(@consultore)
  end



  private
    def set_consultore
      @consultore = Consultore.find(params[:id])
    end

    def consultore_params
      params.require(:consultore).permit(:nombre, :email, :cliente, :proyecto, :user_id, :access)
    end
end

app/helpers/consultores_helper.rb
module ConsultoresHelper
	def radio_button_tag(name, value, checked = false, options = {})
        html_options = { "type" => "radio", "name" => name, "id" => "#{sanitize_to_id(name)}_#{sanitize_to_id(value)}", "value" => value }.update(options.stringify_keys)
        html_options["checked"] = "checked" if checked
        tag :input, html_options
      end
end

app/views/consultores/_form.html.erb
<%= render 'pagina/style' %>
<%= render 'pagina/menuE_left' %>
<%= render 'pagina/content_head' %>
<%= form_for(@consultore) do |f| %>
  <% if @consultore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consultore.errors.count, "error") %> prohibited this consultore from being saved:</h2>

      <ul>
      <% @consultore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1>Nuevo consultor</h1>
  
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre ,:class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email ,:class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_consultora.id %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar consultor', :class => "btn btn-success btn-cons"%>

  </div>
<% end %>

<%= render 'pagina/content_footer' %>

app/views/consultores/_form_asignaciones.html.erb
<%= render 'pagina/style' %>
<%= render 'pagina/menuE_left' %>
<%= render 'pagina/content_head' %>
<h1>Asignaciones </h1>
<%= form_tag :controller => 'consultores', :action => 'crear_asignaciones', :method => 'post' do %>

  <p>
    <div class="field">
    <%= hidden_field_tag :id_consultora, nil, :value => current_consultora.id ,:class => 'form-control tamano' %>
  </div>
  <div class="field">
    <%= label_tag "Email del consultor" %><br>
    <%= text_field_tag :email, nil, :value => @consultore.email ,:class => 'form-control tamano' ,:readonly => true %>
  </div>
  <div class="field">
     <%= label_tag "Clientes" %><br>
    <%= select_tag :cliente, options_for_select(@clientes), prompt: "Selecciona un cliente", :class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= label_tag "Proyectos"%><br>
    <%= select_tag :proyecto, options_for_select(@proyectos), prompt: "Selecciona un proyecto", :class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= label_tag :horaInicio %><br>
    <%= datetime_field_tag :horaInicio, nil, :value => "09:00",:class => 'form-control tamano' %>
  </div>
  <div class="field">
    <%= label_tag :horaFin %><br>
    <%= text_field_tag :horaFin, nil, :value => "18:00",:class => 'form-control tamano' %>
  </div>
    <%= submit_tag "Guardar", :class => "btn btn-success btn-cons" %>
    <%= link_to 'Regresar', consultores_path,  :class => "btn btn-info btn-cons color" %>
  </p>
<% end %>
<%= render 'pagina/content_footer' %>

app/views/consultores/_form_enviar_email.html.erb
<br><p>El usuario no existe, deseas enviarle una invitación para que se registre</p>
 <%= form_tag controller: "consultores", action:  "enviar_email", method: "post" do %>
 <%= text_field_tag :correo, :nil, :value => @email, :class => "form-control tamano", :placeholder => "example@vianse.mx", :required => true, :readonly => true %>
  
 <%= submit_tag "Enviar email" , :class => "btn btn-info btn-cons" %>
 <% end %>

app/views/consultores/_form_invitados.html.erb
<%= render 'pagina/style' %>
<%= render 'pagina/menuE_left' %>
<%= render 'pagina/content_head' %>
<h1>Alta de Invitados</h1>
<hr>

 <%= form_tag controller: "consultores", action:  "acceso", method: "post" do %>
  <div class="field">
    <%= label_tag 'Paso 1: Ingresa el correo electronico del invitado' %><br />
    <%= text_field_tag :correo, nil, :class => "form-control tamano", :placeholder => "example@vianse.mx", :required => true %>
    <%= submit_tag "Aceptar" , :class => "btn btn-success btn-cons" %><br>
    <% end %>
    <% if @leyenda === "N" %>
    <%= render 'form_enviar_email' %>
    <% end %>
    <% if @leyenda === "U" %>
    <%= render 'form_invitados_existentes' %>
    <% end %>
    <% if @leyenda === "C" %>
    <%= render 'form_invitados_existentes' %>
    <% end %>
  </div>

  <h1>Acceso a invitados</h1>
  <hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Usuario invitado</th>
      <th>Acceso a ver las actividades de</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invitados.each do |invitado| %>
      <tr>
        <td><%= invitado.emailInvitado %></td>
        <td><%= invitado.emailConsultor %></td>
        <td><%= link_to 'Quitar', invitado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  

app/views/consultores/_form_invitados_existentes.html.erb
<hr>

  <%= form_for(@invitado) do |f| %>
  <% if @invitado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitado.errors.count, "error") %> prohibited this invitado from being saved:</h2>
      <ul>
      <% @invitado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.hidden_field :id_consultora, :value => current_consultora.id , :class => "form-control tamano"%>
  </div>
  <div class="field">
    <%= f.label "Correo electronico del invitado" %><br>
    <%= f.text_field :emailInvitado, :value => @email , :class => "form-control tamano", :readonly=> true%>
  </div>
  <div class="field">
    <%= f.label "Selecciona un Consultor" %><br>
    <%= f.select(:emailConsultor, @consultores , {include_blank: "Selecciona un Consultor"}, {:class => "form-control tamano",:required => true})%>
  </div>
  <div class="actions">
    <%= f.submit "Dar acceso" %>
  </div>
<% end %>

app/views/consultores/_form_register_user.html.erb
<%= render 'pagina/style' %>
<%= render 'pagina/menuE_left' %>
<%= render 'pagina/content_head' %>
<h1>Generando Login</h1><br>


  <%= form_tag controller: "consultores", action:  "register_user", method: "post" do %>

  <div class="field">
    <%= label_tag 'Correo electronico empresarial' %><br />
    <%= text_field_tag :email, @consultore.email, :class => "form-control tamano"  %>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= password_field_tag :password, nil, :class => "form-control tamano" %>
  </div>

  <div class="field">
    <%= label_tag :password_confirmation %><br />
    <%= password_field_tag :password_confirmation, nil, :class => "form-control tamano" %>
  </div>
 
  <div class="actions">
    <%= submit_tag "Registrar" , :class => "btn btn-success btn-cons"%>
    <%= link_to 'Regresar', consultores_path,  :class => "btn btn-info btn-cons color" %>
  </div>

<% end %>




<%= render 'pagina/content_footer' %>

app/views/consultores/_form_registro_invitados.html.erb
<hr>
<%= form_tag(controller: "consultores", action:  "register_invitados", method: "post") %>

  <div class="field">
    <%= label_tag 'Correo electronico del invitado' %><br />
    <%= text_field_tag :email, @email, :class => "form-control tamano"  %>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= password_field_tag :password, nil, :class => "form-control tamano" %>
  </div>

  <div class="field">
    <%= label_tag :password_confirmation %><br />
    <%= password_field_tag :password_confirmation, nil, :class => "form-control tamano" %>
  </div>

  <%= hidden_field_tag :invitado, true, :class => "form-control tamano" %>
 
  <%= hidden_field_tag :email_consultora, current_consultora.email, :class => "form-control tamano" %><br>
  <div class="actions">
    <%= submit_tag "Registrar" , :class => "btn btn-success btn-cons"%>
    <%= link_to 'Regresar', consultores_path,  :class => "btn btn-info btn-cons color" %>
  </div>

app/views/consultores/_tabla_asignaciones.html.erb
<h1>Listado de Asignaciones</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Proyecto</th>
      <th>Hora inicio</th>
      <th>Hora fin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @asignaciones.each do |asignacione| %>
      <tr>
        <td><%= asignacione.cliente %></td>
        <td><%= asignacione.proyecto %></td>
        <td><%= asignacione.horaInicio %></td>
        <td><%= asignacione.horaFin %></td>
       
        <td><%= link_to 'Eliminar', asignacione, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asignacione', new_asignacione_path %>

app/views/consultores/acceso.html.erb
<%= render 'form_invitados' %>

app/views/consultores/edit.html.erb
<%= render 'form_edit' %>

<%= link_to 'Show', @consultore %> |
<%= link_to 'Back', consultores_path %>

app/views/consultores/index.html.erb
<%= render 'pagina/style' %>
<%= render 'pagina/menuE_left' %>
<%= render 'pagina/content_head' %>

<h1>Mis Consultores</h1>
<h5>Número de Consultores <strong> <%= @consultores.count %></strong></h5>
<%= link_to 'Nuevo Consultor', nuevo_consultor_path,:class => "btn btn-warning btn-cons color" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre del consultor</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @consultores.each do |consultore| %>
      <tr>
        <td><%= consultore.nombre %><span class="badge"><%= @asinaciones %></span></td>
        <td><%= consultore.email %></td>
        <td><%= link_to 'Editar', editar_consultor_path(consultore) %></td>
        <% if consultore.access == true %>
        <td><%= image_tag("http://xikin.googlecode.com/svn-history/r334/trunk/Desarrollo/TT/bin/assets/palomaGrande.png" , height: '32', width: '32') %> </td>
        <% else %>
        <td><%= link_to "Gestionar acceso", register_path(consultore) %></td>

        <% end %>
        <td><%= link_to 'Asignaciones', asignar_path(consultore) %></td>
        <td><%= link_to 'Dar de Baja', consultore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= render 'pagina/content_footer' %>

app/views/consultores/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', consultores_path %>

app/views/consultores/register.html.erb
<%= render 'form_register_user' %>

<%= link_to 'Show', @consultore %> |
<%= link_to 'Back', consultores_path %>

app/views/consultores/show.html.erb
<%= render 'pagina/style' %>
<%= render 'pagina/menuE_left' %>
<%= render 'pagina/content_head' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @consultore.nombre %>
</p>

<p>
  <strong>Email:</strong>
  <%= @consultore.email %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @consultore.cliente %>
</p>

<p>
  <strong>Proyecto:</strong>
  <%= @consultore.proyecto %>
</p>

<p>
  <strong>User:</strong>
  <%= @consultore.user_id %>
</p>

<%= link_to 'Edit', edit_consultore_path(@consultore) %> |
<%= link_to 'Back', consultores_path %>
<%= render 'pagina/content_footer' %>