config/routes.rb
Rpt::Application.routes.draw do
  resources :invitados

  resources :fechas do
    collection { post :import }
  end

  
  resources :asignaciones

  resources :actividades

  resources :consultores

  devise_for :consultoras
  resources :proyectos
  resources :customers
  resources :profiles

  get "dashboard/index"
  get "main/index"
  get "perfil_consultoras" => "profiles#index",:as => "Perfil_Consultoras"
  get '/generando_login_consultor/:id', to: 'consultores#register', :as => "register"
  post '/registrar', :to =>  'consultores#register_user'
  get "dashboard" => "dashboard#index",:as => "Dashboard"
  get "clientes" => "customers#index",:as => "Clientes"
  get "clientes", to: "customers#index", :as => "cliente"
  get "/nuevo_cliente", to: "customers#new", :as => "nuevo"
  get "/editando_cliente/:id", to: "customers#edit", :as => "editar"
  get "proyectos" => "proyectos#index",:as => "Proyectos"
  get '/asignaciones_consultor/:id', to: 'consultores#asignar', :as => "asignar"
  get '/consultor/:id', to: 'consultores#edit', :as => "edit"
  post '/asignar', :to =>  'consultores#crear_asignaciones'
  get "/editando_consultor/:id", to: "consultores#edit", :as => "editar_consultor"
  get "/nuevo_consultor", to: "consultores#new", :as => "nuevo_consultor"
  post '/abrir_periodo', :to =>  'actividades#abrir_periodo'
  get '/acceso', to: 'consultores#acceso', :as => "accesso"
  post '/registrar_invitados', :to =>  'consultores#register_invitados'
  post '/acceso', :to =>  'consultores#acceso'
  post '/enviar_email', :to =>  'consultores#enviar_email'

  

  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: "dashboard#index"

end

app/models/actividade.rb
class Actividade < ActiveRecord::Base
	scope :misasignaciones ,-> (asignacion) {where("email = ?", asignacion)}
	scope :ListadoPrincipal ,-> (asignacion, id_consultor) {where("id_consultora = ? and id_consultor = ?", asignacion, id_consultor )}



end

app/models/asignacione.rb
class Asignacione < ActiveRecord::Base
	scope :misasignaciones ,-> (asignacion) {where("email = ?", asignacion)}
	scope :ListadoPrincipal ,-> (asignacion,email) {where("id = ? and email =?", asignacion,email)}
end

app/models/consultora.rb
class Consultora < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:trackable, :timeoutable, :lockable
  scope :existe ,-> (proyecto) {where("email = ?", proyecto)} 
end

app/models/consultore.rb
class Consultore < ActiveRecord::Base
	has_many :proyectos
	has_many :customers
	belongs_to :user

	scope :misconsultores ,-> (consultor) {where("user_id = ?", consultor)}


	
def to_param

"#{id}-#{nombre.gsub(/(\s)/, '-').gsub(/,|\.|\?|'|"/,'')}"
		
end
    
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :proyectos
	has_many :consultores
	belongs_to :profile
	scope :by_clientes ,-> (customer) {where("user_id = ?", customer)}
	scope :list_clientes ,-> (customer) {where("user_id = ?", customer)}
	
	def to_param
		"#{id}-#{nombre.gsub(/(\s)/, '-').gsub(/,|\.|\?|'|"/,'')}"
		end
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
	belongs_to :profile
end

app/models/fecha.rb
class Fecha < ActiveRecord::Base
#Sirve para la importacion de fechas
 require 'csv'
######

## scope ##
scope :MesActual ,-> (asignacion, id_consultor) {where("mes = ? and año = ?", asignacion, id_consultor )}
########### 

  def self.import(file)
    CSV.foreach(file.path, "r:ISO-8859-1" ) do |row|
      
      @fecha = row[0]
      @mes = row[1]
      @dia = row[2]
      @diaL = row[3]
      @mesl = row[4]
      @ano = row[5]
      
      Fecha.create!(:fecha => @fecha,:mes => @mes, :dia => @dia, :diaL => @diaL, :mesl => @mesl,:año => @ano)

    end # end CSV.foreach
  end # end sel
  
end

app/models/invitado.rb
class Invitado < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	self.inheritance_column = nil
	has_many :customers
	has_many :proyectos
	scope :by_user ,-> (profile) {where("user_id = ?", profile)}
		def to_param
		"#{id}-#{nombre.gsub(/(\s)/, '-').gsub(/,|\.|\?|'|"/,'')}"
		end
	
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
	has_many :customers
	belongs_to :profile
	has_many :consultores

	scope :misproyectos ,-> (proyecto) {where("user_id = ?", proyecto)}

def to_param

"#{id}-#{cliente.gsub(/(\s)/, '-').gsub(/,|\.|\?|'|"/,'')}"
		
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  scope :existe ,-> (proyecto) {where("email = ?", proyecto)}      
end

app/controllers/invitados_controller.rb
class InvitadosController < ApplicationController
  before_action :set_invitado, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @invitados = Invitado.all
    respond_with(@invitados)
  end

  def show
    respond_with(@invitado)
  end

  def new
    @invitado = Invitado.new
    respond_with(@invitado)
  end

  def edit
  end

  def create
    @invitado = Invitado.new(invitado_params)
    @invitado.save
    redirect_to :controller => 'consultores', :action => 'acceso'
    #respond_with(@invitado)
  end

  def update
    @invitado.update(invitado_params)
    respond_with(@invitado)
  end

  def destroy
    @invitado.destroy
    respond_with(@invitado)
  end

  private
    def set_invitado
      @invitado = Invitado.find(params[:id])
    end

    def invitado_params
      params.require(:invitado).permit(:id_consultora, :emailInvitado, :emailConsultor)
    end
end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultores_helper.rb
module ConsultoresHelper
	def radio_button_tag(name, value, checked = false, options = {})
        html_options = { "type" => "radio", "name" => name, "id" => "#{sanitize_to_id(name)}_#{sanitize_to_id(value)}", "value" => value }.update(options.stringify_keys)
        html_options["checked"] = "checked" if checked
        tag :input, html_options
      end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/fechas_helper.rb
module FechasHelper
end

app/helpers/invitados_helper.rb
module InvitadosHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/invitados/_form.html.erb
<%= form_for(@invitado) do |f| %>
  <% if @invitado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitado.errors.count, "error") %> prohibited this invitado from being saved:</h2>

      <ul>
      <% @invitado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_consultora %><br>
    <%= f.text_field :id_consultora %>
  </div>
  <div class="field">
    <%= f.label :emailInvitado %><br>
    <%= f.text_field :emailInvitado %>
  </div>
  <div class="field">
    <%= f.label :emailConsultor %><br>
    <%= f.text_field :emailConsultor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitados/edit.html.erb
<h1>Editing invitado</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitado %> |
<%= link_to 'Back', invitados_path %>

app/views/invitados/index.html.erb
<h1>Listing invitados</h1>

<table>
  <thead>
    <tr>
      <th>Id consultora</th>
      <th>Emailinvitado</th>
      <th>Emailconsultor</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invitados.each do |invitado| %>
      <tr>
        <td><%= invitado.id_consultora %></td>
        <td><%= invitado.emailInvitado %></td>
        <td><%= invitado.emailConsultor %></td>
        <td><%= link_to 'Show', invitado %></td>
        <td><%= link_to 'Edit', edit_invitado_path(invitado) %></td>
        <td><%= link_to 'Destroy', invitado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitado', new_invitado_path %>

app/views/invitados/new.html.erb
<h1>New invitado</h1>

<%= render 'form' %>

<%= link_to 'Back', invitados_path %>

app/views/invitados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id consultora:</strong>
  <%= @invitado.id_consultora %>
</p>

<p>
  <strong>Emailinvitado:</strong>
  <%= @invitado.emailInvitado %>
</p>

<p>
  <strong>Emailconsultor:</strong>
  <%= @invitado.emailConsultor %>
</p>

<%= link_to 'Edit', edit_invitado_path(@invitado) %> |
<%= link_to 'Back', invitados_path %>